### ISSUE TITLE
sse channel as celeby backend

### ISSUE THREAD

**Issue by vinnitu** [singingwolfboy/flask-sse#10]
I want use Celeby to handle tasks with long processing time

Here I read about backend 
http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results

Can I configure this backend to send results to flask-sse channel?

Thanks for any help.

**Comment by singingwolfboy** [comment]
I don't think you can do that. However, you should be able to [chain tasks together](http://docs.celeryproject.org/en/latest/userguide/canvas.html#chains) so that one task receives the return value of another. You can set up a chain so that the the first task returns a result, and the second task takes that result and calls `sse.publish()` on it, to send the result to the Flask-SSE channel. Would that work?
