### ISSUE TITLE
Any idea how to replace redis with AWS SQS ?

### ISSUE THREAD

**Issue by pipozzz** [singingwolfboy/flask-sse#36]
Hello, 

I'm wondering if it's possible to replace redis with AWS SQS.

Thanks for any idea.

**Comment by singingwolfboy** [comment]
You would need to fork this library. All the code is in [`flask_sse.py`](https://github.com/singingwolfboy/flask-sse/blob/main/flask_sse.py), and it's very short. You'll need to modify `ServerSentEventsBlueprint.publish()` and `ServerSentEventsBlueprint.messages()` to talk to SQS instead of Redis.

Good luck!
