### ISSUE TITLE
Pushing notifications when an inactive users becomes active

### ISSUE THREAD

**Issue by bhavaniravi** [singingwolfboy/flask-sse#8]
Does flask-sse provide some kind of queueing for each client to receive notifications that they received when they are inactive?
Can you give me some insights on how to implement this mechanism?

**Comment by singingwolfboy** [comment]
The [server-sent events specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) includes a way to implement a mechanism like that: the `Last-Event-ID` header. When the client connects to the server's event stream, it should be able to provide this header, which tells the server what was the last event that the client saw. The server can then immediately return all the events that have happened since then, and continue streaming events into the future.

However, Flask-SSE does not support this mechanism. In order to support it, you'll need several pieces of functionality:

- A store that can hold on to events, with some rolling window -- perhaps holding the last 5 minutes of events, for example
- A way of assigning IDs to events (timestamps would probably work)
- A way of fetching all events from the store before a certain ID

Once you have all of that, you should be able to subclass the `ServerSentEventsBlueprint` and override the `stream()` method to fetch events from the store before connecting to the `messages()` generator.

Does that make sense? If you _do_ manage to implement this, could you show your code? I'm sure that many other people would be interested.

**Comment by bhavaniravi** [comment]
Thanks ill try it and get back.
